# Generated by Django 4.2.11 on 2025-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profissional_de_saude',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('crm', models.CharField(max_length=16, unique=1)),
                ('coren', models.CharField(max_length=16, unique=1)),
                ('nome', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
