# Generated by Django 4.2.11 on 2025-02-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PEWS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='internacao',
            fields=[
                ('protocolo', models.IntegerField(primary_key=1, serialize=False)),
                ('paciente_crianca_matricula', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEWS.paciente_crianca', verbose_name=''))),
                ('leito', models.CharField(max_length=16)),
                ('dih', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='relatorio_pews',
            fields=[
                ('relatorio_id', models.IntegerField(auto_created=1, primary_key=1, serialize=False)),
                ('internacao_protocolo', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEWS.internacao', verbose_name=''))),
                ('pontuacao_pews', models.IntegerField()),
                ('horario', models.DateTimeField()),
            ],
        ),
    ]
