# Generated by Django 4.2.11 on 2025-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEWS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional_de_saude',
            name='coren',
            field=models.CharField(max_length=16, null=1, unique=1),
        ),
        migrations.AlterField(
            model_name='profissional_de_saude',
            name='crm',
            field=models.CharField(max_length=16, null=1, unique=1),
        ),
        migrations.AlterField(
            model_name='profissional_de_saude',
            name='id',
            field=models.IntegerField(auto_created=1, primary_key=1, serialize=False),
        ),
    ]
